name: example
description: Flutter Mediator Simple Demostration.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_mediator_simple:
    path: ../
  flutter_i18n: ^0.32.4
  shared_preferences: ^2.0.17 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/flutter_i18n/