name: flutter_mediator_simple
description: A reactive state management package for Flutter. It's simple, efficient and easy to use.
version: 1.2.1
homepage: https://github.com/rob333/flutter_mediator_simple

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
