name: flutter_mediator_simple
description: A state management package for flutter. Simple, efficient and easy to use.
version: 1.0.1
homepage: https://github.com/rob333/flutter_mediator_simple

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
